repos:
  # - repo: https://github.com/gozynta/pre-commit-hooks
  #   rev: ""
  #   hooks:
  #     - id: check-poetry-sources
  #     - id: check-python-versions-match
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: pretty-format-json
        exclude: ^Pipfile.lock$
        args:
          - "--autofix"
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
        exclude: "^.gitlab-ci.yml"
      # Need --unsafe for .gitlab-ci.yml due to gitlab's custom !reference tag
      # This check may be redundant since invalidly formed yaml will make check-python-versions-match.py fail
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
          - "--unsafe"
        files: "^.gitlab-ci.yml"
      - id: check-merge-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: no-commit-to-branch
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: Tiltfile$
        types_or: [file]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: "^pytests/"
  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.0
    hooks:
      - id: poetry-sort
