repos:
  - repo: local
    hooks:
      - id: check-python-versions-match
        name: Check that python versions match
        language: python
        entry: dev-scripts/check-python-versions-match.py
        additional_dependencies:
          - "PyYAML"
          - "pipfile"
          - "typer"
          # Needed until typer fixes https://github.com/tiangolo/typer/issues/377
          - "click<8.1.0"
      - id: check-poetry-sources
        name: Check poetry sources
        language: python
        entry: dev-scripts/check-poetry-sources.py
        additional_dependencies:
          - "toml"
          - "typer"
          # Needed until typer fixes https://github.com/tiangolo/typer/issues/377
          - "click<8.1.0"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: pretty-format-json
        exclude: ^Pipfile.lock$
        args:
          - "--autofix"
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
        exclude: "^.gitlab-ci.yml"
      # Need --unsafe for .gitlab-ci.yml due to gitlab's custom !reference tag
      # This check may be redundant since invalidly formed yaml will make check-python-versions-match.py fail
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
          - "--unsafe"
        files: "^.gitlab-ci.yml"
      - id: check-merge-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: no-commit-to-branch
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "^pytests/"
