apiVersion: v1
kind: Namespace
metadata:
  name: gozynta-boilerplate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-alpine
  namespace: gozynta-boilerplate
spec:
  selector:
    matchLabels:
      app: boilerplate-alpine
  template:
    metadata:
      labels:
        app: boilerplate-alpine
    spec:
      containers:
      - name: boilerplate-alpine
        image: gozynta/boilerplate-alpine
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-debian
  namespace: gozynta-boilerplate
spec:
  selector:
    matchLabels:
      app: boilerplate-debian
  template:
    metadata:
      labels:
        app: boilerplate-debian
    spec:
      containers:
      - name: boilerplate-debian
        image: gozynta/boilerplate-debian
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
