#!/bin/bash

# Exit script on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

# The old build script is dead, long live pre-commit (or not, if something better comes along)
./dev-scripts/migrate-to-pre-commit
