#!/bin/bash

# Run this to enable all git hooks for this project.

# Exit script on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

./dev-scripts/setup-pipenv-link
./dev-scripts/migrate-to-pre-commit
