#!/bin/bash

# Run this to enable all git hooks for this project.

# Exit script on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

# Save this script's directory to a variable
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Change directory to repository root.
cd "${SCRIPT_DIR}/.."

# If there's an existing symlink, remove it.
if [[ -L .git/hooks ]] ; then
  rm .git/hooks
fi

if command -v pre-commit > /dev/null; then
    pre-commit install --install-hooks
elif [ -f pyproject.toml ] && (grep 'tool.poetry.dependencies' pyproject.toml > /dev/null); then
    poetry run pre-commit install --install-hooks
elif [ -f Pipfile ]; then
    pipenv run pre-commit install --install-hooks
fi
