#!/bin/bash

# Link {project}/.venv to pipenv's virtualenv.  This gives us a way to refer to the venv from VSCode's configuration.

# Exit script on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

# Link .venv unless user has already set pipenv to use project directory.
set +u
[ -z "{PIPENV_VENV_IN_PROJECT}" ] && ln -s `pipenv --venv` .venv
set -u
