#!/bin/bash

# Link {project}/.venv to pipenv's virtualenv.  This gives us a way to refer to the venv from VSCode's configuration.

# Exit script on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

ln -s `pipenv --venv` .venv
