analytics_settings(True)
disable_snapshots()

local_resource('pipenv', 'pipenv install -d', deps=['Pipfile'])

PROJECT_ROOT = '..'

def all_pysrc_py_files(project_root):
    return str(local('find pysrc/ -type f -name "*.py"', dir=project_root)).strip().split('\n')

def all_pytest_py_files(project_root):
    return str(local('find pytests/ -type f -name "*.py"', dir=project_root)).strip().split('\n')

def all_git_files(project_root):
    return str(local('git ls-files', dir=project_root)).strip().split('\n')

# Run tests
test(
    'pytest',
    'pipenv run coverage run --source=pysrc -m pytest',
    dir='..',
    deps=all_pysrc_py_files(PROJECT_ROOT)+all_pytest_py_files(PROJECT_ROOT),
    resource_deps=['pipenv'],
    labels=['test'],
    )
test(
    'coverage',
    'pipenv run coverage report -m',
    dir='..',
    deps=all_pysrc_py_files(PROJECT_ROOT)+all_pytest_py_files(PROJECT_ROOT),
    resource_deps=['pytest'],
    labels=['test'],
    )
test(
    'pre-commit',
    'pipenv run pre-commit run --all-files --color always',
    dir='..',
    deps=all_git_files(PROJECT_ROOT),
    resource_deps=['pipenv'],
    labels=['test'],
)
